---
- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: eda-demo
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      # action:
      #   debug:
      action:
        run_playbook:
          name: playbooks/k8s-playbook.yaml
          extra_vars:
            event: "{{ event }}"
